// Date: 01/11/2014 19:43:18
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.bowser.robotic.common.techne;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class BaseTorse extends ModelBiped
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape26;
    ModelRenderer Shape27;
    ModelRenderer Shape28;
    ModelRenderer Shape29;
    ModelRenderer Shape30;
    ModelRenderer Shape31;
    ModelRenderer Shape32;
    ModelRenderer Shape33;
    ModelRenderer Shape34;
    ModelRenderer Shape35;
    ModelRenderer Shape36;
    ModelRenderer Shape37;
    ModelRenderer Shape38;
    ModelRenderer Shape39;
    ModelRenderer Shape40;
    ModelRenderer Shape41;
    ModelRenderer Shape42;
    ModelRenderer Shape43;
    ModelRenderer Shape44;
    ModelRenderer Shape45;
    ModelRenderer Shape46;
    ModelRenderer Shape47;
    ModelRenderer Shape48;
    ModelRenderer Shape49;
  
  public BaseTorse(float expand)
  {
    //textureWidth = 128;
    //textureHeight = 128;
      super(expand, 0, 128, 128);
    
      
      Shape1 = new ModelRenderer(this, 0, 18);
      Shape1.addBox(0F, 0F, 0F, 10, 2, 4);
      Shape1.setRotationPoint(-5F, 10F, -1F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 16, 0);
      Shape2.addBox(0F, 0F, 0F, 5, 4, 1);
      Shape2.setRotationPoint(-2.5F, 2F, -3F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 29, 0);
      Shape3.addBox(0F, 0F, 0F, 3, 10, 1);
      Shape3.setRotationPoint(-1.5F, 0F, 2F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 38, 0);
      Shape4.addBox(0F, 0F, 0F, 1, 7, 1);
      Shape4.setRotationPoint(3F, -0.4F, 2F);
      Shape4.setTextureSize(128, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0.3717861F);
      Shape5 = new ModelRenderer(this, 43, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape5.setRotationPoint(-1.9F, 5.3F, -3F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0.7853982F);
      Shape6 = new ModelRenderer(this, 48, 0);
      Shape6.addBox(0F, 0F, 0F, 1, 9, 2);
      Shape6.setRotationPoint(3F, 1F, -0.5F); //(8F, 3F, -0.5F)
      Shape6.setTextureSize(128, 128);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 55, 0);
      Shape7.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape7.setRotationPoint(3F, 5F, -1.5F); //(8F, 6F, -1.5F)
      Shape7.setTextureSize(128, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 57);
      Shape8.addBox(0F, 0F, 0F, 1, 3, 3);
      Shape8.setRotationPoint(3F, -2F, -1.5F); //(8F, 0F, -1.5F)
      Shape8.setTextureSize(128, 128);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 9, 60);
      Shape9.addBox(-2F, 0F, -2F, 4, 2, 1);
      Shape9.setRotationPoint(0F, 10F, -1F); //(-2F, 22F, -1F)
      Shape9.setTextureSize(128, 128);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 20, 56);
      Shape10.addBox(-2F, 0F, -2F, 1, 2, 5);
      Shape10.setRotationPoint(-1F, 10F, -1F); //(-3F, 22F, -1F)
      Shape10.setTextureSize(128, 128);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 43, 6);
      Shape11.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape11.setRotationPoint(3F, -0.4F, -3F);
      Shape11.setTextureSize(128, 128);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0.3717861F);
      Shape12 = new ModelRenderer(this, 55, 4);
      Shape12.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape12.setRotationPoint(-4F, -0.1F, -3F);
      Shape12.setTextureSize(128, 128);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, -0.3839724F);
      Shape13 = new ModelRenderer(this, 33, 57);
      Shape13.addBox(0F, 0F, 0F, 1, 1, 5);
      Shape13.setRotationPoint(3.2F, 8.1F, -2F);
      Shape13.setTextureSize(128, 128);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, -0.7853982F);
      Shape14 = new ModelRenderer(this, 46, 57);
      Shape14.addBox(0F, 0F, 0F, 1, 1, 5);
      Shape14.setRotationPoint(-3.3F, 8.1F, -2F);
      Shape14.setTextureSize(128, 128);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 2.338741F);
      Shape15 = new ModelRenderer(this, 60, 0);
      Shape15.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape15.setRotationPoint(1.1F, 6F, -3F);
      Shape15.setTextureSize(128, 128);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, -0.7853982F);
      Shape16 = new ModelRenderer(this, 10, 57);
      Shape16.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape16.setRotationPoint(1F, 7.6F, 2F);
      Shape16.setTextureSize(128, 128);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 0, 54);
      Shape17.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape17.setRotationPoint(-4F, 7.6F, 2F);
      Shape17.setTextureSize(128, 128);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 59, 55);
      Shape18.addBox(0F, 0F, 0F, 1, 7, 1);
      Shape18.setRotationPoint(-4F, -0.1F, 2F);
      Shape18.setTextureSize(128, 128);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, -0.3839724F);
      Shape19 = new ModelRenderer(this, 0, 48);
      Shape19.addBox(0F, 0F, 0F, 1, 1, 4);
      Shape19.setRotationPoint(-4F, -0.1F, -2F);
      Shape19.setTextureSize(128, 128);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, -0.3839724F);
      Shape20 = new ModelRenderer(this, 11, 50);
      Shape20.addBox(0F, 0F, 0F, 1, 1, 4);
      Shape20.setRotationPoint(3F, -0.4F, -2F);
      Shape20.setTextureSize(128, 128);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0.3717861F);
      Shape21 = new ModelRenderer(this, 22, 52);
      Shape21.addBox(-2F, 0F, -2F, 4, 2, 1);
      Shape21.setRotationPoint(0F, 10F, -1F); //(2F, 22F, -1F)
      Shape21.setTextureSize(128, 128);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 33, 49);
      Shape22.addBox(-2F, 0F, -2F, 1, 2, 5);
      Shape22.setRotationPoint(4F, 10F, -1F); //(6F, 22F, -1F)
      Shape22.setTextureSize(128, 128);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 46, 47);
      Shape23.addBox(0F, 0F, 0F, 1, 7, 2);
      Shape23.setRotationPoint(2F, 3F, -0.5F); //(4F, 15F, -0.5F)
      Shape23.setTextureSize(128, 128);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      Shape24 = new ModelRenderer(this, 60, 6);
      Shape24.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape24.setRotationPoint(2F, 5F, -1.5F); //(4F, 17F, -1.5F)
      Shape24.setTextureSize(128, 128);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, 0F);
      Shape25 = new ModelRenderer(this, 54, 48);
      Shape25.addBox(0F, 0F, 0F, 1, 3, 3);
      Shape25.setRotationPoint(2F, 0F, -1.5F); //(4F, 12F, -1.5F)
      Shape25.setTextureSize(128, 128);
      Shape25.mirror = true;
      setRotation(Shape25, 0F, 0F, 0F);
      Shape26 = new ModelRenderer(this, 0, 42);
      Shape26.addBox(0F, 0F, 0F, 3, 1, 4);
      Shape26.setRotationPoint(1F, 10F, -2F); //(6F, 12F, -2F)
      Shape26.setTextureSize(128, 128);
      Shape26.mirror = true;
      setRotation(Shape26, 0F, 0F, 0F);
      Shape27 = new ModelRenderer(this, 0, 32);
      Shape27.addBox(0F, 0F, 0F, 1, 7, 2);
      Shape27.setRotationPoint(-3F, 3F, -0.5F); //(-5F, 15F, -0.5F)
      Shape27.setTextureSize(128, 128);
      Shape27.mirror = true;
      setRotation(Shape27, 0F, 0F, 0F);
      Shape28 = new ModelRenderer(this, 15, 46);
      Shape28.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape28.setRotationPoint(-3F, 5F, -1.5F); //(-5F, 17F, -1.5F)
      Shape28.setTextureSize(128, 128);
      Shape28.mirror = true;
      setRotation(Shape28, 0F, 0F, 0F);
      Shape29 = new ModelRenderer(this, 23, 45);
      Shape29.addBox(0F, 0F, 0F, 1, 3, 3);
      Shape29.setRotationPoint(-3F, 0F, -1.5F); //
      Shape29.setTextureSize(128, 128);
      Shape29.mirror = true;
      setRotation(Shape29, 0F, 0F, 0F);
      Shape30 = new ModelRenderer(this, 15, 42);
      Shape30.addBox(0F, 0F, 0F, 18, 1, 1);
      Shape30.setRotationPoint(-9F, -1F, -0.5F); //(-9F, -1F, -0.5F)
      Shape30.setTextureSize(128, 128);
      Shape30.mirror = true;
      setRotation(Shape30, 0F, 0F, 0F);
      Shape31 = new ModelRenderer(this, 7, 36);
      Shape31.addBox(0F, 0F, 0F, 3, 1, 4);
      Shape31.setRotationPoint(-4F, 10F, -2F); //(-9F, 12F, -2F)
      Shape31.setTextureSize(128, 128);
      Shape31.mirror = true;
      setRotation(Shape31, 0F, 0F, 0F);
      Shape32 = new ModelRenderer(this, 55, 36);
      Shape32.addBox(0F, 0F, 0F, 1, 9, 2);
      Shape32.setRotationPoint(-4F, 1F, -0.5F); //(-9F, 3F, -0.5F)
      Shape32.setTextureSize(128, 128);
      Shape32.mirror = true;
      setRotation(Shape32, 0F, 0F, 0F);
      Shape33 = new ModelRenderer(this, 22, 35);
      Shape33.addBox(0F, 0F, 0F, 1, 3, 3);
      Shape33.setRotationPoint(-4F, -2F, -1.5F); //(-9F, 0F, -1.5F)
      Shape33.setTextureSize(128, 128);
      Shape33.mirror = true;
      setRotation(Shape33, 0F, 0F, 0F);
      Shape34 = new ModelRenderer(this, 33, 45);
      Shape34.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape34.setRotationPoint(-4F, 5F, -1.5F); //(-9F, 6F, -1.5F)
      Shape34.setTextureSize(128, 128);
      Shape34.mirror = true;
      setRotation(Shape34, 0F, 0F, 0F);
      /**Shape35 = new ModelRenderer(this, 31, 36);
      Shape35.addBox(0F, 0F, 0F, 5, 3, 2);
      Shape35.setRotationPoint(-2.5F, 1F, 2F);
      Shape35.setTextureSize(128, 128);
      Shape35.mirror = true;
      setRotation(Shape35, 0F, 0F, 0F);
      Shape36 = new ModelRenderer(this, 0, 7);
      Shape36.addBox(0F, 0F, 0F, 7, 6, 3);
      Shape36.setRotationPoint(-3.5F, 4F, 2F);
      Shape36.setTextureSize(128, 128);
      Shape36.mirror = true;
      setRotation(Shape36, 0F, 0F, 0F);*/
      Shape37 = new ModelRenderer(this, 20, 75);
      Shape37.addBox(0F, 0F, 0F, 2, 3, 1);
      Shape37.setRotationPoint(-1F, -3F, -6F);
      Shape37.setTextureSize(128, 128);
      Shape37.mirror = true;
      setRotation(Shape37, 0F, 0F, 0F);
      Shape38 = new ModelRenderer(this, 0, 0);
      Shape38.addBox(0F, 0F, 0F, 6, 2, 0);
      Shape38.setRotationPoint(-3F, -6F, -5F);
      Shape38.setTextureSize(128, 128);
      Shape38.mirror = true;
      setRotation(Shape38, 0F, 0F, 0F);
      Shape39 = new ModelRenderer(this, 0, 4);
      Shape39.addBox(0F, 0F, 0F, 4, 1, 0);
      Shape39.setRotationPoint(-2F, -4F, -5F);
      Shape39.setTextureSize(128, 128);
      Shape39.mirror = true;
      setRotation(Shape39, 0F, 0F, 0F);
      Shape40 = new ModelRenderer(this, 0, 65);
      Shape40.addBox(0F, 0F, 0F, 1, 8, 8);
      Shape40.setRotationPoint(-5F, -8F, -4F);
      Shape40.setTextureSize(128, 128);
      Shape40.mirror = true;
      setRotation(Shape40, 0F, 0F, 0F);
      Shape41 = new ModelRenderer(this, 0, 82);
      Shape41.addBox(0F, 0F, 0F, 1, 8, 8);
      Shape41.setRotationPoint(4F, -8F, -4F);
      Shape41.setTextureSize(128, 128);
      Shape41.mirror = true;
      setRotation(Shape41, 0F, 0F, 0F);
      Shape42 = new ModelRenderer(this, 0, 99);
      Shape42.addBox(0F, 0F, 0F, 10, 8, 1);
      Shape42.setRotationPoint(-5F, -8F, 4F);
      Shape42.setTextureSize(128, 128);
      Shape42.mirror = true;
      setRotation(Shape42, 0F, 0F, 0F);
      Shape43 = new ModelRenderer(this, 0, 110);
      Shape43.addBox(0F, 0F, 0F, 10, 1, 9);
      Shape43.setRotationPoint(-5F, -9F, -4F);
      Shape43.setTextureSize(128, 128);
      Shape43.mirror = true;
      setRotation(Shape43, 0F, 0F, 0F);
      Shape44 = new ModelRenderer(this, 0, 122);
      Shape44.addBox(0F, 0F, 0F, 8, 2, 1);
      Shape44.setRotationPoint(-4F, -8F, -5F);
      Shape44.setTextureSize(128, 128);
      Shape44.mirror = true;
      setRotation(Shape44, 0F, 0F, 0F);
      Shape45 = new ModelRenderer(this, 19, 90);
      Shape45.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape45.setRotationPoint(3F, -6F, -5F);
      Shape45.setTextureSize(128, 128);
      Shape45.mirror = true;
      setRotation(Shape45, 0F, 0F, 0F);
      Shape46 = new ModelRenderer(this, 19, 82);
      Shape46.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape46.setRotationPoint(-4F, -6F, -5F);
      Shape46.setTextureSize(128, 128);
      Shape46.mirror = true;
      setRotation(Shape46, 0F, 0F, 0F);
      Shape47 = new ModelRenderer(this, 23, 122);
      Shape47.addBox(0F, 0F, 0F, 6, 3, 1);
      Shape47.setRotationPoint(-3F, -3F, -5F);
      Shape47.setTextureSize(128, 128);
      Shape47.mirror = true;
      setRotation(Shape47, 0F, 0F, 0F);
      Shape48 = new ModelRenderer(this, 20, 66);
      Shape48.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape48.setRotationPoint(-3F, -4F, -5F);
      Shape48.setTextureSize(128, 128);
      Shape48.mirror = true;
      setRotation(Shape48, 0F, 0F, 0F);
      Shape49 = new ModelRenderer(this, 24, 106);
      Shape49.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape49.setRotationPoint(2F, -4F, -5F);
      Shape49.setTextureSize(128, 128);
      Shape49.mirror = true;
      setRotation(Shape49, 0F, 0F, 0F);
      

      //ajouter le bras entier
      this.bipedLeftArm.addChild(Shape6);
      this.bipedLeftArm.addChild(Shape8);
      this.bipedLeftArm.addChild(Shape7);
      this.bipedLeftArm.addChild(Shape26);
      
      this.bipedRightArm.addChild(Shape32);
      this.bipedRightArm.addChild(Shape33);
      this.bipedRightArm.addChild(Shape34);
      this.bipedRightArm.addChild(Shape31);
      
      //this.bipedBody.addChild(Shape35);
      //this.bipedBody.addChild(Shape36);
      this.bipedBody.addChild(Shape1);
      this.bipedBody.addChild(Shape2);
      this.bipedBody.addChild(Shape3);
      this.bipedBody.addChild(Shape4);
      this.bipedBody.addChild(Shape5);
      this.bipedBody.addChild(Shape30);
      this.bipedBody.addChild(Shape11);
      this.bipedBody.addChild(Shape18);
      this.bipedBody.addChild(Shape12);
      this.bipedBody.addChild(Shape13);
      this.bipedBody.addChild(Shape14);
      this.bipedBody.addChild(Shape15);
      this.bipedBody.addChild(Shape16);
      this.bipedBody.addChild(Shape17);
      this.bipedBody.addChild(Shape20);
      this.bipedBody.addChild(Shape19);
      
      this.bipedLeftLeg.addChild(Shape23);
      this.bipedLeftLeg.addChild(Shape22);
      this.bipedLeftLeg.addChild(Shape21);
      this.bipedLeftLeg.addChild(Shape24);
      this.bipedLeftLeg.addChild(Shape25);
      
      this.bipedRightLeg.addChild(Shape27);
      this.bipedRightLeg.addChild(Shape10);
      this.bipedRightLeg.addChild(Shape9);
      this.bipedRightLeg.addChild(Shape29);
      this.bipedRightLeg.addChild(Shape28);
      
      
      this.bipedHead.addChild(Shape37);
      this.bipedHead.addChild(Shape38);
      this.bipedHead.addChild(Shape39);
      this.bipedHead.addChild(Shape40);
      this.bipedHead.addChild(Shape41);
      this.bipedHead.addChild(Shape42);
      this.bipedHead.addChild(Shape43);
      this.bipedHead.addChild(Shape44);
      this.bipedHead.addChild(Shape45);
      this.bipedHead.addChild(Shape46);
      this.bipedHead.addChild(Shape47);
      this.bipedHead.addChild(Shape48);
      this.bipedHead.addChild(Shape49);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  

}
