// Date: 24/10/2014 10:36:05
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.bowser.robotic.common;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class FourArc extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
  
  public FourArc()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 16, 24);
      Shape1.addBox(0F, 0F, 0F, 16, 1, 8);
      Shape1.setRotationPoint(-8F, 23F, 0F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 42, 44);
      Shape2.addBox(0F, 0F, 0F, 6, 15, 5);
      Shape2.setRotationPoint(-3F, 9F, -6F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 14, 0);
      Shape3.addBox(0F, 0F, 0F, 12, 15, 2);
      Shape3.setRotationPoint(-6F, 9F, 1.3F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 10);
      Shape4.addBox(0F, 0F, 0F, 1, 15, 4);
      Shape4.setRotationPoint(-7F, 9F, -2F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 31);
      Shape5.addBox(0F, 0F, 0F, 2, 9, 6);
      Shape5.setRotationPoint(6F, 15F, -3F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 31);
      Shape6.addBox(0F, 0F, 0F, 2, 9, 6);
      Shape6.setRotationPoint(-8F, 15F, -3F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 14, 0);
      Shape7.addBox(0F, 0F, 0F, 12, 15, 2);
      Shape7.setRotationPoint(-6F, 9F, -3.3F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 46, 4);
      Shape8.addBox(-3F, 0F, 0F, 3, 15, 4);
      Shape8.setRotationPoint(3F, 9F, -6F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0.8499753F, 0F);
      Shape9 = new ModelRenderer(this, 46, 4);
      Shape9.addBox(0F, 0F, 0F, 3, 15, 4);
      Shape9.setRotationPoint(-3F, 9F, -6F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, -0.8499753F, 0F);
      Shape10 = new ModelRenderer(this, 42, 44);
      Shape10.addBox(0F, 0F, 0F, 6, 15, 5);
      Shape10.setRotationPoint(-3F, 9F, 1F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 46, 4);
      Shape11.addBox(0F, 0F, 0F, 3, 15, 4);
      Shape11.setRotationPoint(4F, 9F, 1.1F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, -0.8499753F, 0F);
      Shape12 = new ModelRenderer(this, 46, 4);
      Shape12.addBox(-3F, 0F, 0F, 3, 15, 4);
      Shape12.setRotationPoint(-4F, 9F, 1.1F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0.8499753F, 0F);
      Shape13 = new ModelRenderer(this, 17, 34);
      Shape13.addBox(0F, 0F, 0F, 2, 8, 2);
      Shape13.setRotationPoint(6F, 16F, 1F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0.2792527F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 17, 34);
      Shape14.addBox(0F, 0F, -2F, 2, 8, 2);
      Shape14.setRotationPoint(6F, 16F, -1F);
      Shape14.setTextureSize(64, 32);
      Shape14.mirror = true;
      setRotation(Shape14, -0.2792527F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 17, 34);
      Shape15.addBox(0F, 0F, 0F, 2, 8, 2);
      Shape15.setRotationPoint(-8F, 16F, 1F);
      Shape15.setTextureSize(64, 32);
      Shape15.mirror = true;
      setRotation(Shape15, 0.2792527F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 17, 34);
      Shape16.addBox(0F, 0F, -2F, 2, 8, 2);
      Shape16.setRotationPoint(-8F, 16F, -1F);
      Shape16.setTextureSize(64, 32);
      Shape16.mirror = true;
      setRotation(Shape16, -0.2792527F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 0, 10);
      Shape17.addBox(0F, 0F, 0F, 1, 15, 4);
      Shape17.setRotationPoint(6F, 9F, -2F);
      Shape17.setTextureSize(64, 32);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 43, 0);
      Shape18.addBox(0F, 0F, 0F, 6, 1, 2);
      Shape18.setRotationPoint(-3F, 18F, -8F);
      Shape18.setTextureSize(64, 32);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 0, 0);
      Shape19.addBox(0F, 0F, 0F, 1, 4, 2);
      Shape19.setRotationPoint(-3F, 14F, -8F);
      Shape19.setTextureSize(64, 32);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 43, 0);
      Shape20.addBox(0F, 0F, 0F, 6, 1, 2);
      Shape20.setRotationPoint(-3F, 13F, -8F);
      Shape20.setTextureSize(64, 32);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 0, 0);
      Shape21.addBox(0F, 0F, 0F, 1, 4, 2);
      Shape21.setRotationPoint(2F, 14F, -8F);
      Shape21.setTextureSize(64, 32);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 16, 24);
      Shape22.addBox(0F, 0F, 0F, 16, 1, 8);
      Shape22.setRotationPoint(-8F, 23F, -8F);
      Shape22.setTextureSize(64, 32);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 34, 33);
      Shape23.addBox(0F, 0F, 0F, 12, 1, 3);
      Shape23.setRotationPoint(-6F, 9F, -1.5F);
      Shape23.setTextureSize(64, 32);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      Shape24 = new ModelRenderer(this, 26, 38);
      Shape24.addBox(0F, 0F, 0F, 4, 1, 4);
      Shape24.setRotationPoint(-2F, 8F, -2F);
      Shape24.setTextureSize(64, 32);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, 0F);
  }
  
  public void render(float f)
  {
    Shape1.render(f);
    Shape2.render(f);
    Shape3.render(f);
    Shape4.render(f);
    Shape5.render(f);
    Shape6.render(f);
    Shape7.render(f);
    Shape8.render(f);
    Shape9.render(f);
    Shape10.render(f);
    Shape11.render(f);
    Shape12.render(f);
    Shape13.render(f);
    Shape14.render(f);
    Shape15.render(f);
    Shape16.render(f);
    Shape17.render(f);
    Shape18.render(f);
    Shape19.render(f);
    Shape20.render(f);
    Shape21.render(f);
    Shape22.render(f);
    Shape23.render(f);
    Shape24.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  

}
